using System.Collections.Immutable;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Meridian.SchemaGen;

// Emits a compile-time hash of each on-disk cache model's shape into a
// Meridian.Models.SchemaHashes class. A store compares the hash baked into its
// build against the hash stored in a cache file; a mismatch is treated as a
// cache miss so stale-shaped data never gets read back.
//
// The hash is derived from each public instance property's *serialized* name
// (honoring [JsonPropertyName] and the camelCase policy the stores use) + fully
// qualified type, sorted by name. Comments, whitespace, and declaration order
// are therefore irrelevant — only the on-disk shape moves the hash. Hashing the
// serialized name (not the C# identifier) means a naming-policy change or a
// [JsonPropertyName] rename — which changes the on-disk keys — also invalidates
// stale caches. Adding/removing/retyping a property changes the hash too;
// forgetting to "bump a version" is no longer possible.
//
// Note: the SchemaHash property each wrapper carries is itself a public instance
// property, so it participates in its own model's hash. That's stable and
// harmless; only the static CurrentSchemaHash is excluded (static properties
// aren't serialized).
//
// TODO: the walk is flat. If a model gains a property whose type is another of
// our own complex types, only that type's *name* contributes, not its inner
// shape. All current cache models have primitive/BCL property types, so this is
// fine; revisit (recurse into same-assembly types) if that changes.
[Generator(LanguageNames.CSharp)]
public sealed class CacheSchemaGenerator : IIncrementalGenerator
{
    private const string AttributeName = "Meridian.Models.CacheSchemaAttribute";

    private const string AttributeSource = """
        // <auto-generated/>
        #nullable enable
        namespace Meridian.Models
        {
            /// <summary>
            /// Marks a type whose serialized shape is persisted to the on-disk cache.
            /// The schema generator emits a stable hash of its properties into
            /// <c>Meridian.Models.SchemaHashes</c>.
            /// </summary>
            [global::System.AttributeUsage(global::System.AttributeTargets.Class | global::System.AttributeTargets.Struct, AllowMultiple = false, Inherited = false)]
            internal sealed class CacheSchemaAttribute : global::System.Attribute
            {
            }
        }
        """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // The attribute is generated, so consumers never reference the generator
        // assembly just to annotate a type.
        context.RegisterPostInitializationOutput(ctx =>
            ctx.AddSource("CacheSchemaAttribute.g.cs", SourceText.From(AttributeSource, Encoding.UTF8)));

        var models = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeName,
                predicate: static (node, _) => node is TypeDeclarationSyntax,
                transform: static (ctx, _) => Describe((INamedTypeSymbol)ctx.TargetSymbol))
            .Collect();

        context.RegisterSourceOutput(models, static (ctx, descriptors) =>
            ctx.AddSource("SchemaHashes.g.cs", SourceText.From(Emit(descriptors), Encoding.UTF8)));
    }

    private readonly record struct ModelDescriptor(string Name, string Hash);

    private static ModelDescriptor Describe(INamedTypeSymbol type)
    {
        var canonical = type.GetMembers()
            .OfType<IPropertySymbol>()
            .Where(p => p.DeclaredAccessibility == Accessibility.Public
                        && !p.IsStatic
                        && !p.IsIndexer)
            .Select(p => SerializedName(p) + ":" + p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))
            .OrderBy(s => s, global::System.StringComparer.Ordinal);

        var joined = string.Join("\n", canonical);
        return new ModelDescriptor(type.Name, ShortHash(joined));
    }

    // The on-disk key for a property: an explicit [JsonPropertyName("...")] wins,
    // otherwise the camelCase policy the cache stores configure on their
    // JsonSerializerContext. Mirrors System.Text.Json's JsonCamelCaseNamingPolicy
    // (lowercase the leading run of uppercase letters, but only up to the last
    // one if a non-upper follows).
    private static string SerializedName(IPropertySymbol p)
    {
        foreach (var attr in p.GetAttributes())
        {
            if (attr.AttributeClass?.ToDisplayString() == "System.Text.Json.Serialization.JsonPropertyNameAttribute"
                && attr.ConstructorArguments.Length == 1
                && attr.ConstructorArguments[0].Value is string name)
                return name;
        }
        return CamelCase(p.Name);
    }

    private static string CamelCase(string name)
    {
        if (name.Length == 0 || !char.IsUpper(name[0]))
            return name;

        var chars = name.ToCharArray();
        for (var i = 0; i < chars.Length; i++)
        {
            if (i > 0 && i + 1 < chars.Length && !char.IsUpper(chars[i + 1]))
                break;
            chars[i] = char.ToLowerInvariant(chars[i]);
        }
        return new string(chars);
    }

    private static string ShortHash(string input)
    {
        using var sha = SHA256.Create();
        var bytes = sha.ComputeHash(Encoding.UTF8.GetBytes(input));
        var sb = new StringBuilder(16);
        // First 8 bytes -> 16 hex chars. 64 bits of collision resistance is far
        // more than enough to distinguish schema revisions.
        for (var i = 0; i < 8; i++)
            sb.Append(bytes[i].ToString("x2"));
        return sb.ToString();
    }

    private static string Emit(ImmutableArray<ModelDescriptor> descriptors)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("namespace Meridian.Models");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>Compile-time hashes of cache model shapes. See CacheSchemaGenerator.</summary>");
        sb.AppendLine("    internal static class SchemaHashes");
        sb.AppendLine("    {");
        foreach (var d in descriptors.OrderBy(d => d.Name, global::System.StringComparer.Ordinal))
            sb.AppendLine($"        public const string {d.Name} = \"{d.Hash}\";");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }
}
