param(
    [string]$SecretsJson,
    [string]$OutputFile
)

$j = Get-Content $SecretsJson -Raw | ConvertFrom-Json
$id = $j.installed.client_id
$sec = $j.installed.client_secret

$content = @"
// <auto-generated/> do not edit, generated from client_secret.json
namespace Meridian.Auth;

internal static class GoogleSecrets
{
    internal const string ClientId = "$id";
    internal const string ClientSecret = "$sec";
}
"@

Set-Content -Path $OutputFile -Encoding UTF8 -Value $content
