param(
    [string]$SecretsJson,
    [string]$OutputFile
)

# Fail the build loudly on any error rather than emitting a half-formed
# Secrets.g.cs. ConvertFrom-Json on a malformed file would otherwise leave $j
# null and we'd silently write empty credentials that only break at runtime.
$ErrorActionPreference = 'Stop'

$j = Get-Content $SecretsJson -Raw | ConvertFrom-Json
$id = $j.installed.client_id
$sec = $j.installed.client_secret

if ([string]::IsNullOrEmpty($id) -or [string]::IsNullOrEmpty($sec)) {
    throw "client_id/client_secret missing from $SecretsJson (expected .installed.client_id and .installed.client_secret)."
}

# Escape for a C# regular (double-quoted) string literal: backslash first, then
# quote. Without this a value containing " or \ would emit a syntactically broken
# Secrets.g.cs. Real Google credentials don't contain these, but a malformed or
# swapped-in file shouldn't produce a baffling compile error.
function Format-CSharpLiteral([string]$value) {
    # Build the escaped literal char-by-char. PowerShell's [string]::Replace
    # overload resolution is unreliable for single-char find arguments (it may
    # bind to (char,char) and silently skip the replacement), so we avoid it and
    # the regex -replace operator entirely. Backslash and double-quote are the
    # only chars that break a C# regular string literal for these values.
    $sb = [System.Text.StringBuilder]::new()
    foreach ($ch in $value.ToCharArray()) {
        if ($ch -eq [char]'\' -or $ch -eq [char]'"') {
            [void]$sb.Append([char]'\')
        }
        [void]$sb.Append($ch)
    }
    return $sb.ToString()
}

$idLiteral = Format-CSharpLiteral $id
$secLiteral = Format-CSharpLiteral $sec

# Single-quoted here-string so PowerShell does not interpolate $ inside the
# values; placeholders are filled via -f after escaping.
$template = @'
// <auto-generated/> do not edit, generated from client_secret.json
namespace Meridian.Auth;

internal static class GoogleSecrets
{{
    internal const string ClientId = "{0}";
    internal const string ClientSecret = "{1}";
}}
'@

$content = $template -f $idLiteral, $secLiteral

Set-Content -Path $OutputFile -Encoding UTF8 -Value $content
